### ISSUE TITLE
[feature request] drop ca descriptors

### ISSUE THREAD

**Issue by stefansaraev** [gfto/tsdecrypt#5]
would be nice to filter out all ca descriptors from pmt after descrambling.

**Comment by gfto** [comment]
This means rewriting the PMT which I don't want to do (since I don't need that functionality for my own use). I know that some broken devices that think since there is a CA descriptor the stream must be encrypted (they shown LOCK picture) but these devices are really broken. If somebody sends me clean patch I'll apply it thou, I just don't need that myself enough to bother implementing it. (mptsd have code that recreates pmt).

**Comment by stefansaraev** [comment]
no problem with the equipment here, its just annoying, and I can filter out in the multiplexer, but is still annoying :)
thanks for the mptsd hint, I'll see what I can do myself.

**Comment by gfto** [comment]
I was counting that users were filtering them in the MUX ;)

**Comment by stefansaraev** [comment]
lets close this. makes no sense to keep open. uh ;)
